### ISSUE TITLE
ls broke

### ISSUE THREAD

**Issue by bostrt** [bostrt/quikey#16]
```
Traceback (most recent call last):
  File "/home/rbost/.local/bin/qk", line 11, in <module>
    sys.exit(cli())
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rbost/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rbost/.local/lib/python3.6/site-packages/quikey/quikey.py", line 86, in ls
    tags = ', '.join([x.name for x in phrase.get('tags')])
  File "/home/rbost/.local/lib/python3.6/site-packages/quikey/quikey.py", line 86, in <listcomp>
    tags = ', '.join([x.name for x in phrase.get('tags')])
AttributeError: 'str' object has no attribute 'name'
```

**Comment by bostrt** [comment]
Forgot to update `name` to `key` during a bunch of changes.

**Comment by bostrt** [comment]
Could probably stand to make some unit tests...
