### ISSUE TITLE
xdg-4 update breaks environment variables

### ISSUE THREAD

**Issue by bostrt** [bostrt/quikey#17]
````
# pip3 install -U --user quikey
...
Installing collected packages: xdg, quikey
  Found existing installation: xdg 3.0.2
    Uninstalling xdg-3.0.2:
      Successfully uninstalled xdg-3.0.2
  Found existing installation: quikey 0.0.5
    Uninstalling quikey-0.0.5:
      Successfully uninstalled quikey-0.0.5
Successfully installed quikey-0.0.6 xdg-4.0.0
# qk ls
Traceback (most recent call last):
  File "/home/rbost/.local/bin/qk", line 11, in <module>
    sys.exit(cli())
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rbost/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rbost/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rbost/.local/lib/python3.6/site-packages/quikey/quikey.py", line 27, in cli
    ctx.obj = {'database': get_database()}
  File "/home/rbost/.local/lib/python3.6/site-packages/quikey/quikey.py", line 20, in get_database
    appDirs = AppDirectories() # XDG folders
  File "/home/rbost/.local/lib/python3.6/site-packages/quikey/directories.py", line 6, in __init__
    self.data = XDG_DATA_HOME + '/quikey/'
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

````

**Comment by bostrt** [comment]
https://github.com/srstevenson/xdg/commit/51ae263077413b6e5cd2d44e14619db8f27d9b99
