### ISSUE TITLE
Doesn't run on Manjaro (Unstable)

### ISSUE THREAD

**Issue by xircon** [bostrt/quikey#29]
```
 qk start
Traceback (most recent call last):
  File "/usr/bin/qk", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'xdg' distribution was not found and is required by quikey
```
Any ideas?

**Comment by xircon** [comment]
Pip works, it is just the aur package that doesn't.

**Comment by bostrt** [comment]
Thanks for the report! I'll sync up with @SanskritFritz tonight since they
built the package.

**Comment by SanskritFritz** [comment]
Yeah, sorry, please see https://github.com/bostrt/quikey/commit/592337434ad85da737dcfa1ed97d0aab9d5f94ad for the possible cause. So this means the package is actually broken now :cry: but fixing the dependency will cure it.

**Comment by SanskritFritz** [comment]
I guess this ticket can be closed then.
