### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by asterlab** [bostrt/quikey#31]
cat qkdaemon.log 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/quikey-0.1.2a0-py3.7.egg/quikey/filewatch.py", line 24, in run
    observer.notify()
  File "/usr/local/lib/python3.7/dist-packages/quikey-0.1.2a0-py3.7.egg/quikey/qkdaemon.py", line 30, in notify
    self.init_phrase_handlers()
  File "/usr/local/lib/python3.7/dist-packages/quikey-0.1.2a0-py3.7.egg/quikey/qkdaemon.py", line 25, in init_phrase_handlers
    phrases = self.db.all()
  File "/usr/local/lib/python3.7/dist-packages/quikey-0.1.2a0-py3.7.egg/quikey/models.py", line 31, in all
    return self.db.all()
  File "/usr/local/lib/python3.7/dist-packages/tinydb-3.15.0-py3.7.egg/tinydb/database.py", line 438, in all
    return list(itervalues(self._read()))
  File "/usr/local/lib/python3.7/dist-packages/tinydb-3.15.0-py3.7.egg/tinydb/database.py", line 411, in _read
    return self._storage.read()
  File "/usr/local/lib/python3.7/dist-packages/tinydb-3.15.0-py3.7.egg/tinydb/database.py", line 90, in read
    raw_data = self._storage.read() or {}
  File "/usr/local/lib/python3.7/dist-packages/tinydb-3.15.0-py3.7.egg/tinydb/storages.py", line 116, in read
    return json.load(self._handle)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 17 (char 16)

**Comment by bostrt** [comment]
Hi @asterlab! I will have to see if I can reproduce something similar. 

If you are able, can you please upload your phrase database (`qk status` should show you). Please redact any data you do not want public on the internet. I ask for this because it looks like a JSON parser error was reached and I am curious if Quikey introduced the error or something else.

**Comment by bostrt** [comment]
Good evening @asterlab, I'm not sure what led to the exception you saw in this report so will need to see your phrase database as mentioned in the last comment. Please note the part about redacting any data you do not want to share.

**Comment by bostrt** [comment]
Following-up on this, @asterlab can you share a redacted version of your quikey database?

**Comment by bostrt** [comment]
@asterlab I will have to archive this issue but if you are able to share a redacted version of your database, I would be very interesting it testing it on my side.
