### ISSUE TITLE
qk start gives 'Invalid MIT-MAGIC-COOKIE-1 key'

### ISSUE THREAD

**Issue by SanskritFritz** [bostrt/quikey#47]
I installed quikey 0.1.3 via pip on Archlinux.
I'm running Plasma, try to start quikey daemon in Konsole from Fish:

```
frank@HomeC ~> qk start
Traceback (most recent call last):
  File "/usr/bin/quikey-daemon", line 33, in <module>
    sys.exit(load_entry_point('quikey==0.1.3', 'console_scripts', 'quikey-daemon')())
  File "/usr/bin/quikey-daemon", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/quikey/qkdaemon.py", line 2, in <module>
    from pynput.keyboard import Key, Listener, KeyCode, Controller
  File "/usr/lib/python3.8/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/usr/lib/python3.8/site-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/usr/lib/python3.8/site-packages/pynput/keyboard/_xorg.py", line 39, in <module>
    from pynput._util.xorg import (
  File "/usr/lib/python3.8/site-packages/pynput/_util/xorg.py", line 40, in <module>
    _check()
  File "/usr/lib/python3.8/site-packages/pynput/_util/xorg.py", line 38, in _check
    display = Xlib.display.Display()
  File "/usr/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.8/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'
frank@HomeC ~> echo $DISPLAY
:0
frank@HomeC ~> xauth list
HomeC/unix:1  MIT-MAGIC-COOKIE-1  7a5822c1c16859c4695e643acba3fd5c
HomeC/unix:1  MIT-MAGIC-COOKIE-1  7a5822c1c16859c4695e643acba3fd5c
HomeC/unix:2  MIT-MAGIC-COOKIE-1  433380f40613d6aaa062c277c16becd0
HomeC/unix:3  MIT-MAGIC-COOKIE-1  437b84c73117f91b052127a041564d68
HomeC/unix:3  MIT-MAGIC-COOKIE-1  437b84c73117f91b052127a041564d68
HomeC/unix:3  MIT-MAGIC-COOKIE-1  437b84c73117f91b052127a041564d68
HomeC/unix:0  MIT-MAGIC-COOKIE-1  cc094967bbae43727abac666c0fcb270
HomeC/unix:0  MIT-MAGIC-COOKIE-1  4c3422523d61268c3195527b05508e26
HomeC/unix:0  MIT-MAGIC-COOKIE-1  4c3422523d61268c3195527b05508e26
HomeC/unix:0  MIT-MAGIC-COOKIE-1  4c3422523d61268c3195527b05508e26
HomeC/unix:0  MIT-MAGIC-COOKIE-1  4c3422523d61268c3195527b05508e26

```

**Comment by bostrt** [comment]
Thanks for reporting this! Can you show me what version of `pynput` you have?

**Comment by SanskritFritz** [comment]
```
root@HomeC /C/B/borg# pip show pynput
Name: pynput
Version: 1.4.5
Summary: Monitor and control user input devices
Home-page: https://github.com/moses-palmer/pynput
Author: Moses Palmér
Author-email: moses.palmer@gmail.com
License: LGPLv3
Location: /usr/lib/python3.8/site-packages
Requires: python-xlib, six
Required-by: quikey
```

**Comment by bostrt** [comment]
Are you running through SSH by chance?

**Comment by SanskritFritz** [comment]
> Are you running through SSH by chance?

No, that would explain it. I'm in a plain local X session using Plasma ($DISPLAY is my proof). I can start any other X application from the same shell, including pyhon ones, for example pzl_games.

**Comment by SanskritFritz** [comment]
I had a feeling that the identical xauth list entries could be problematic. So I logged out, removed all xauth entries, logged back in, and voilá, qk start works again perfectily :smile:
