### ISSUE TITLE
Archlinux - Python update python 3.8.6-1 -> 3.9.0-1 breaks quikey

### ISSUE THREAD

**Issue by xircon** [bostrt/quikey#50]
Working on it, but this is the error:
```
qk edit
Traceback (most recent call last):
  File "/usr/bin/qk", line 33, in <module>
    sys.exit(load_entry_point('quikey==0.1.6a0', 'console_scripts', 'qk')())
  File "/usr/bin/qk", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/quikey/quikey.py", line 5, in <module>
    import humanize
  File "/usr/lib/python3.9/site-packages/humanize/__init__.py", line 2, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pick' distribution was not found and is required by quikey
```
Just when it was running perfectly :D

:edit:
Potentially: 
```
cat 2020-12-02T08:14 | grep dis
python-distlib 0.3.1-1 -> 0.3.1-2
python-distro 1.5.0-1 -> 1.5.0-3
```
I record each update in a timed and dated file.

**Comment by bostrt** [comment]
Hmm first thing I notice is `quikey==0.1.6a0`. Are you using a git clone or was this installed through the Arch repo? 

I'll see about getting some Python 3.9 tests running.

**Comment by xircon** [comment]
quikey-git aur package.

**Comment by xircon** [comment]
OK rebuilt all the dependent packages (a lot are in aur) and now working.
This is my command history:
```
1638  yay python-pick
 1639  yay python-pick
 1641  yay pynput
 1643  yay tinydb
 1645  yay inotify
```
They all had to be rebuilt one by one as quikey reported errors.  Will mark as solverd.
